"use client";

/** Play free offline Telugu speech generated by the app's eSpeak NG endpoint. */
export async function playOfflineTelugu(text: string, language: string): Promise<boolean> {
  if (language !== "te" || !text.trim()) return false;
  try {
    const response = await fetch("/api/tts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text, language }),
    });
    if (!response.ok) return false;
    const audioUrl = URL.createObjectURL(await response.blob());
    const audio = new Audio(audioUrl);
    audio.onended = () => URL.revokeObjectURL(audioUrl);
    audio.onerror = () => URL.revokeObjectURL(audioUrl);
    await audio.play();
    return true;
  } catch {
    return false;
  }
}
